### ISSUE TITLE
add to cli --out option

### ISSUE THREAD

**Issue by Oloompa** [morintd/ts-generate-schema#9]
- **I'm submitting a ...**
  [ ] bug report
  [X] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Salut, ton outils réponds à un besoin que j'ai de pouvoir dynamiser la création de schéma pour un fichier de configuration. Cependant je constate qu'en l'état il génère un répertoire à l'emplacement du fichier cible. 

Peux tu ajouter un paramètrage pour le répertoire de sorti `--out` qui permettrait de changer le répertoire (chemin compris) de sorti ?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by Oloompa** [comment]
Suite à un test je constate que j'arrive à obtenir le résultat souhaité en commençant le chemin par `**/`.

Si mon fichier cible est  `./src/foo/bar.ts` et que je souhaite que le schéma soit généré dans `./schema`, je dois utiliser en cible `**/foo/bar.ts`.

Avant je ciblais directement `src/foo/bar.ts` ce qui générait le répertoire schéma dans `./src/foo`.

**Comment by morintd** [comment]
This feature has just been added in `v2.1.0`, thanks for your submission.
